services:
  iiif-static-choices-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
      # Mount all source code for development
      - ./docker-gui/web-interface:/app/docker-gui/web-interface
      - ./data:/app/data
      - ./iiif:/app/iiif
      - ./mirador:/app/mirador
      - ./openseadragon:/app/openseadragon
      - ./tiler:/app/tiler
      - ./manifest:/app/manifest
      - ./examples:/app/examples
      # Prevent node_modules conflicts by using anonymous volume
      - /app/docker-gui/web-interface/node_modules
      # Mount Python files for development
      - ./server.py:/app/server.py
      - ./iiif_generator.py:/app/iiif_generator.py
    env_file:
      - .env.dev
    environment:
      - NODE_ENV=development
      - PYTHONUNBUFFERED=1
      - SERVER_URL=${SERVER_URL:-http://localhost:8000}
    restart: unless-stopped
    # Command modified to create symbolic links (adapted for development)
    command: bash -c "mkdir -p /app/data/iiif && cp /app/docker-gui/iiif-server-for-docker-app.py /app/data/server.py && ln -sf /app/iiif/manifest /app/data/iiif/manifest && ln -sf /app/iiif/image /app/data/iiif/image && ln -sf /app/data/viewers /app/viewers && ln -sf /app/data/public /app/public && ln -sf /app/mirador /app/data/mirador && cd /app/docker-gui/web-interface && npm run dev & sleep 5 && cd /app && python /app/data/server.py 8000"
    deploy:
      resources:
        limits:
          memory: 12G
        reservations:
          memory: 8G
    networks:
      - iiif-dev-network

networks:
  iiif-dev-network:
    driver: bridge
