[project]
name = "iiif-tiler-py"
version = "1.0"
description = ""
requires-python  = ">=3.12"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "pyyaml>=6.0.1,<7",
    "pillow>=12.2.0,<13",
    "numpy>=2.4.6",
]


